#!/usr/bin/env bash
# installing and config nginx

apt-get update
apt-get -y install nginx

# adding a html page
echo "Holberton School" > /var/www/html/index.html

CONFIG=\
"server {
	listen 80 default_server;
  	listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
	server_name _;
        location / {
                try_files \$uri \$uri/ =404;
	}
	location /redirect_me{
        	rewrite ^/redirect_me(.*)$ http://www.youtube.com/ permanent;
	}
}"

echo -e "$CONFIG" > /etc/nginx/sites-enabled/default

# checking if service is running
state=$(pgrep nginx)
if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
echo "done"
